-- =======================================================
-- Florya MEV Koleji - Depo ve Stok Takip Uygulaması
-- Supabase Cloud Veritabanı Şeması (PostgreSQL)
-- =======================================================

-- 1. Kullanıcılar Tablosu (Users)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'personel', -- 'admin' veya 'personel'
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Kategoriler Tablosu (Categories)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

-- 3. Ürünler ve Stok Kartları (Products / Items)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(100) UNIQUE,
    product_code VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    unit VARCHAR(30) NOT NULL DEFAULT 'Adet', -- 'Kg', 'Litre', 'Adet', 'Koli', 'Teneke', 'Paket'
    current_stock NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    critical_threshold NUMERIC(12, 2) NOT NULL DEFAULT 5.0,
    unit_price NUMERIC(12, 2) DEFAULT 0.0,
    storage_location VARCHAR(100) DEFAULT 'Kuru Depo', -- 'Kuru Depo', 'Soğuk Hava Deposu (+4°C)', 'Donuk Depo (-18°C)', 'Kantin Deposu', 'Mutfak Hazırlık'
    expiry_date DATE,
    lot_no VARCHAR(100),
    notes TEXT,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Stok Hareketleri ve Denetim İzi (Stock Movements Audit Trail)
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    movement_type VARCHAR(50) NOT NULL, -- 'GİRİŞ', 'ÇIKIŞ', 'SAYIM DÜZELTME', 'FİRE / İMHA'
    quantity NUMERIC(12, 2) NOT NULL,
    previous_stock NUMERIC(12, 2) NOT NULL,
    new_stock NUMERIC(12, 2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    document_no VARCHAR(100), -- İrsaliye No, Fatura No, Fiş No
    reason TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Başlangıç İndeksleri
CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_storage_location ON public.products(storage_location);
CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at ON public.stock_movements(created_at DESC);

-- RLS (Row Level Security) - Opsiyonel
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for application key" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow public read-write for application key" ON public.products FOR ALL USING (true);
CREATE POLICY "Allow public read-write for application key" ON public.stock_movements FOR ALL USING (true);
